# Generated by Django 4.2.20 on 2026-07-20 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='folder', help_text='One emoji or icon character, e.g. cat or 1F600', max_length=20, verbose_name='Icon (emoji)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Audio (mp3)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Total questions')),
                ('correct', models.IntegerField(default=0, verbose_name='Correct answers')),
                ('quiz_type', models.CharField(default='image_to_name', help_text='image_to_name or name_to_image', max_length=20, verbose_name='Quiz type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz attempt',
                'verbose_name_plural': 'Quiz attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False, verbose_name='Learned')),
                ('view_count', models.IntegerField(default=1, verbose_name='View count')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='Last viewed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.item', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learning progress',
                'verbose_name_plural': 'Learning progress',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
