# Generated by Django 4.2.20 on 2026-07-20 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '学习模块', 'verbose_name_plural': '学习模块'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'sort_order', 'id'], 'verbose_name': '学习条目', 'verbose_name_plural': '学习条目'},
        ),
        migrations.AlterModelOptions(
            name='learningprogress',
            options={'verbose_name': '学习进度', 'verbose_name_plural': '学习进度'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-created_at'], 'verbose_name': '测验记录', 'verbose_name_plural': '测验记录'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', help_text='一个 emoji 或图标字符', max_length=20, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='item',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='语音文件 (mp3)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.item', verbose_name='学习条目'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='最近查看'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='learned',
            field=models.BooleanField(default=False, verbose_name='已学会'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='view_count',
            field=models.IntegerField(default=1, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='学习模块'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='correct',
            field=models.IntegerField(default=0, verbose_name='答对数'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(choices=[('image_to_name', '看图选名'), ('name_to_image', '看名选图')], default='image_to_name', max_length=20, verbose_name='测验类型'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total',
            field=models.IntegerField(default=0, verbose_name='总题数'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
