# Generated by Django 4.2.20 on 2026-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='item',
            name='fact',
            field=models.TextField(blank=True, default='', help_text='点击可播放语音的科普说明文字', verbose_name='科普知识'),
        ),
    ]
