# Generated by Django 4.2.20 on 2026-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_english_name_item_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='表情符号'),
        ),
    ]
