# Generated by Django 4.2.20 on 2026-07-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audio_en',
            field=models.FileField(blank=True, null=True, upload_to='audio_en/', verbose_name='英文语音'),
        ),
        migrations.AddField(
            model_name='item',
            name='audio_fact',
            field=models.FileField(blank=True, null=True, upload_to='audio_fact/', verbose_name='科普语音'),
        ),
        migrations.AlterField(
            model_name='item',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='中文语音'),
        ),
    ]
