# Generated by Django 4.2.20 on 2026-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_audio_en_item_audio_fact_alter_item_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_position',
            field=models.CharField(blank=True, default='center center', help_text='CSS object-position，如 center top / 50% 30%', max_length=30, verbose_name='图片焦点'),
        ),
    ]
