# Generated by Django 4.2.20 on 2026-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_position',
        ),
        migrations.AddField(
            model_name='item',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='图片平均色+60%黑, 如 #2a1a0f', max_length=7, verbose_name='背景色'),
        ),
    ]
