# Generated by Django 4.2.20 on 2026-07-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_image_position_item_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bg_color',
        ),
        migrations.AddField(
            model_name='item',
            name='image_position',
            field=models.CharField(blank=True, default='50% 50%', help_text='自动检测的视觉中心, CSS object-position 格式', max_length=30, verbose_name='图片焦点'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_position_checked',
            field=models.BooleanField(default=False, help_text='是否已经自动检测过图片视觉中心', verbose_name='焦点已检测'),
        ),
    ]
