# Generated by Django 4.2.20 on 2026-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_item_bg_color_item_image_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='image_position_ipad',
            field=models.CharField(blank=True, default='50% 50%', help_text='iPad 专用图片焦点, CSS object-position 格式', max_length=30, verbose_name='iPad 图片焦点'),
        ),
        migrations.AlterField(
            model_name='item',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='表情符号'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item_progress'),
        ),
    ]
