# Generated by Django 6.0.7 on 2026-07-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ipad_portrait_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, choices=[('farm', '🏠 家里和农场'), ('wild', '🌍 野生动物'), ('ocean', '🌊 海洋动物'), ('reptile', '🦎 爬虫和昆虫')], default='', help_text='浏览模式中按组分开展示', max_length=20, verbose_name='浏览分组'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_position_ipad_portrait',
            field=models.CharField(blank=True, default='50% 50%', help_text='iPad 竖屏图片焦点, CSS object-position 格式', max_length=30, verbose_name='iPad 竖屏焦点'),
        ),
    ]
