# Generated by Django 6.0.7 on 2026-07-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_group_alter_item_image_position_ipad_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.JSONField(blank=True, default=dict, help_text='浏览分组定义，格式 {"key": "🏠 名称"}。由种子数据写入。', verbose_name='分组配置'),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, default='', help_text='浏览模式分组 key，需在所属 Category.groups 中定义', max_length=20, verbose_name='浏览分组'),
        ),
    ]
